title: "Birce Altın"                      #TODO: BLOG TITLE
email:                                    #TODO: BLOG EMAIL
description: "Birce Altın's personal blog" #TODO: BLOG DESCRIPTION
timezone: UTC+2
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo50.png'
favicon: 'assets/images/logo60.png'
author: Birce Altın
paginate: 30
locale: tr_TR
lang: tr_TR
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: compressed

# Authors
authors:
  birc:
    name: Birce Altın
    display_name: Birce Altın
    avatar: 'assets/images/logo60.png'
    email:
    web: "/about/"
    instagram:
    description:

# Social
social:
  instagram:
  facebook:
  twitter:

# Plugins
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
