title: "Birce Altın"
email: birceealtin@gmail.com
description: "Birce Altın's personal blog"
timezone: UTC+2
baseurl: ""
permalink: "/:title/"
logo: 'assets/images/logo75.png'
favicon: 'assets/images/logo75.png'
author: Birce Altın
paginate: 30
disqus: 'demowebsite'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: compressed

# Authors
authors:
  birc:
    name: Birce Altın
    display_name: Birce Altın
    avatar:
    email: birceealtin@gmail.com
    web:
    twitter:
    description:

# Social
social:
  instagram:
  facebook:
  twitter:

# Plugins
plugins:
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
